basePath: /api
host: localhost:8080
info:
  contact: {}
  description: This is a loyalty service server.
  title: Loyalty Service API
  version: "1.0"
paths:
  /campaigns:
    get:
      consumes:
      - application/json
      description: Get all campaigns
      responses:
        "200":
          description: Ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            type: string
      summary: Get all campaigns
      tags:
      - campaigns
  /campaigns/:campaignId:
    put:
      consumes:
      - application/json
      description: Get all campaigns
      parameters:
      - description: ID of the campaign to update
        in: path
        name: campaignId
        required: true
        type: string
      responses:
        "200":
          description: Ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            type: string
      summary: Get all campaigns
      tags:
      - campaigns
swagger: "2.0"
