version: '3.8'

volumes:
  postgres-local:
    driver: local
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-local
    restart: always
    ports:
      - 8888:8888
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8888 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
