version: '3.8'

volumes:
  postgres-local:
    driver: local
services:
  # db:
  #   image: postgres
  #   container_name: database-pg-local
  #   restart: always
  #   volumes:
  #     - postgres-local:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
  #     POSTGRES_DB: ${APP_DATABASE_NAME}
  #     POSTGRES_USER: ${APP_DATABASE_USER}
  #   ports:
  #     - ${APP_DATABASE_PORT}:5432
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U ${APP_DATABASE_USER}']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-local
    restart: always
    ports:
      - 8888:8888
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8888 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
